# This is a basic workflow to help you get started with Actions

name: DV8 Analysis

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.3.4

      - name: DV8 analysis
        id: dv8
        uses: archtimize/dv8-action@master
        with: 
          license_key: ${{ secrets.LICENSE_KEY }}
          activation_code: ${{ secrets.ACTIVATION_CODE }}
          source_language: java
          project_path: /github/workspace/
          result_path: dv8-output

      # Store the DV8 results as an artifact in the workflow
      - name: Store DV8 analysis
        uses: actions/upload-artifact@v2
        with:
          name: dv8-output
          path: dv8-output
